import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// COMPONENTS
import Navbar from "./components/Navbar";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Harmony Management System",
  description: "Generated by Oz with love.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interSans.variable} antialiased h-screen w-screen flex`}
      >
        <Navbar />
        <main className="bg-paper-background w-full h-full flex flex-1">
          {children}
        </main>
      </body>
    </html>
  );
}
